export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bitsugar/bin"
export SHELL="zsh"
export EDITOR="/usr/bin/vi"
export PAGER="/usr/bin/less"
export HISTFILE="$HOME/.zsh_history"
export SAVEHIST="1000"
export PS1='%n@%m:%~> '

umask 022

# nice keybindings
bindkey -v
bindkey ' ' magic-space
bindkey "^I" expand-or-complete-prefix
bindkey '\eq' push-input
bindkey -s '^p' '\eqpwd\n'

precmd () {print -Pn "\e]0;%n@%m: %~\a"}

# history
setopt hist_ignore_dups
setopt append_history
setopt bare_glob_qual

# root alias
alias root='su root -c "export HOME=$HOME; exec $SHELL"'
